### ISSUE TITLE
Supplying an external reference table doesn't bypass all previous steps

### ISSUE THREAD

**Issue by gtsambos** [mertensu/ABrox#2]
Hi again!

I'm having some trouble getting ABrox to run with an externally supplied reference table. 
It looks as if the `sumStatObsData` object created [here](https://github.com/mertensu/ABrox/blob/master/abrox/core/abc.py#L57) is needed to create the `pp` object [here](https://github.com/mertensu/ABrox/blob/master/abrox/core/abc.py#L66), which is later used in the `run()` method [here](https://github.com/mertensu/ABrox/blob/master/abrox/core/abc_mcmc.py#L77) regardless of whether an external reference table is supplied or not.

This leads to `NoneType` errors like the following:

```
6200D-132482-M:3.abrox-output gtsambos$ python analysis_2019-09-06-11-52-35.py
Traceback (most recent call last):
  File "analysis_2019-09-06-11-52-35.py", line 59, in <module>
    abc.run()
  File "/Users/gtsambos/miniconda3/lib/python3.6/site-packages/abrox/core/abc.py", line 57, in run
    sumStatObsData = summarizer.summarize(obsData)
  File "/Users/gtsambos/miniconda3/lib/python3.6/site-packages/abrox/core/abc_summary.py", line 13, in summarize
    return self.summary(data).flatten()
AttributeError: 'NoneType' object has no attribute 'flatten'
```
(Note: I haven't supplied a raw data file because I don't want ABRox to use my raw data - I want it to use the transformed data that is in my provided reference table).

I'm not sure whether this is because of a bug, or if it's just because I haven't changed all the necessary fields in my analysis.py files -- what do you think? If it is a code issue, I'm happy to fork the repo and make any necessary changes if you can point me in the right direction 😄

**Comment by gtsambos** [comment]
btw, I'm still getting this problem when I explicitly subset the summary statistics from my reference table and provide them as inputs. Here is the script I've been working with:

```
"""
This is an automatically generated script by ABrox GUI.
Created on 2019-09-06 14:13:03.708435.
"""

# Required imports
import numpy as np
from scipy import stats
from abrox.core.abc import Abc


def summary(data):
    # write your code here
    datafile = np.loadtxt("/Users/gtsambos/Projects/aus-ABC/output/1.transformed-stats/truth.stats.pls.csv",
                delimiter=",", skiprows=1)
    return(datafile)


def simulate_Model1(params):
    # write your code here
    # pass
    datafile = np.loadtxt("/Users/gtsambos/Projects/aus-ABC/output/2.abrox-input/sim.datafile.csv",
                delimiter=",", skiprows=1)
    return(datafile)


CONFIG = {
    "data": {
        "datafile": "/Users/gtsambos/Projects/aus-ABC/output/2.abrox-input/sim.datafile.csv",
        "delimiter": ","
    },
    "models": [
        {
        "name": "Model1",
        "priors": [
        ],
        "simulate": simulate_Model1
        },
    ],
    "summary": summary,
    "distance": None,
    "settings": {
        'distance_metric': 'default',
         'method': {'algorithm': 'mcmc',
                    'specs': {'burn': 0,
                              'chl': 10000,
                              'keep': 100,
                              'proposal': None,
                              'start': None,
                              'thin': 1,
                              'threshold': None}},
         'objective': 'inference',
         'outputdir': '/Users/gtsambos/Projects/aus-ABC/output/3.abrox-output',
         'reftable': {'extref': '/Users/gtsambos/Projects/aus-ABC/output/2.abrox-input/sim.reference_table.csv',
                      'simulations': 10000},
         'test': {'fixed': {}, 'model': None}
    }
}


if __name__ == "__main__":
    # Create and run an Abc instance
    abc = Abc(config=CONFIG)
    abc.run()

```

**Comment by mertensu** [comment]
Hi Georgia,

I can take a closer look at it but before I do, can you add a print statement into your summary function right after the file has been loaded to show the shape of _datafile_ . It seems to me that the file isn't imported correctly.

**Comment by gtsambos** [comment]
Sorry for the late reply to this! `print(datafile.shape)` gives `(10,)` as output. (I have 10 summary statistics, btw)

**Comment by mertensu** [comment]
It seems to me that your observed data are not imported correctly. If a path to a file is specified (as in your case), ABrox tries to import this file using:

```
pd.read_csv(self.config['data']['datafile'], engine='python',
                            delimiter=self.config['data']['delimiter']).as_matrix()
```

Could you try to run this command directly on your observed dataset (_"/Users/gtsambos/Projects/aus-ABC/output/2.abrox-input/sim.datafile.csv"_) using ',' as the delimiter and see what it returns?
